services:
  db:
    build: 
      context: ./db/
    restart: on-failure
    ports:
      - "3306:3306"
    env_file: "db.docker.env"
    volumes:
      - "./db/data:/var/lib/mysql"
      - "./db/sql:/docker-entrypoint-initdb.d"
    networks:
      - my-network
  backend:
    build: 
      context: ./backend/
    environment:
      NODE_ENV: production
    env_file:
      - ".docker.env"
      - "db.docker.env"
    ports:
      - "8000:8000"
    networks:
      - my-network
    develop:
      watch:
        - action: rebuild
          path: ./backend/
          target: /usr/src/app/
          ignore:
            - node_modules
networks:
  my-network:
